<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2022" started-at="2020-07-30T10:57:29Z" finished-at="2020-07-30T10:57:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2022" started-at="2020-07-30T10:57:29Z" finished-at="2020-07-30T10:57:31Z">
      <class name="jiraIssueApi.getexistingJiraIssue">
        <test-method status="PASS" signature="baseTest()[pri:0, instance:jiraIssueApi.getexistingJiraIssue@12d3a4e9]" name="baseTest" is-config="true" duration-ms="388" started-at="2020-07-30T16:27:29Z" finished-at="2020-07-30T16:27:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseTest -->
        <test-method status="FAIL" signature="getExistingIssueList()[pri:0, instance:jiraIssueApi.getexistingJiraIssue@12d3a4e9]" name="getExistingIssueList" duration-ms="1620" started-at="2020-07-30T16:27:29Z" finished-at="2020-07-30T16:27:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at apiVerification.apiVerification.responseCodeValiddation(apiVerification.java:24)
	at jiraIssueApi.getexistingJiraIssue.getExistingIssueList(getexistingJiraIssue.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getExistingIssueList -->
      </class> <!-- jiraIssueApi.getexistingJiraIssue -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
